### ISSUE TITLE
Issues with rollup config

### ISSUE THREAD

**Issue by ludviglundgren** [ts-bps/ts-react-component#1]
Hello! Nice project!

I had some issues with the rollup config.
It doesn't output an `index.js` file, only `index.cjs.js` and `index.esm.js`. And in `package.json`, main  is set to `dist/index.js` so it does not work when imported in another project, or the demo.

So with a `rollup.config.js` with this it works as intended.

```
  output: [
    {
      file: "dist/index.js",
      format: "cjs"
    },
    {
      file: "dist/index.m.js",
      format: "esm"
    }
  ],
```

Maybe there was an other expected behaviour.

**Comment by rakannimer** [comment]
Hey @ludviglundgren,

Thanks for catching and reporting this issue. 

I fixed it by changing the default package.json to use .cjs.js and .esm.js 

Your solution is also perfectly valid, I just prefer to be more explicit in the module format. 

Cheers !

**Comment by ludviglundgren** [comment]
No problem! I'll use your settings then i think! 👍
